/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lab6p2_mariocalix_22041098;

import java.awt.Color;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import javax.swing.DefaultComboBoxModel;
import javax.swing.DefaultListModel;
import javax.swing.JColorChooser;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.tree.DefaultMutableTreeNode;
import javax.swing.tree.DefaultTreeModel;

/**
 *
 * @author mario
 */
public class Lab6P2_MarioCalix_22041098 extends javax.swing.JFrame {

    /**
     * Creates new form Lab6P2_MarioCalix_22041098
     */
    public Lab6P2_MarioCalix_22041098() {
        initComponents();
        this.setExtendedState(MAXIMIZED_BOTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jd_ingresar = new javax.swing.JDialog();
        jTabbedPane4 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        tf_nombrep = new javax.swing.JTextField();
        jButton4 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jl_pokemones = new javax.swing.JList();
        jScrollPane2 = new javax.swing.JScrollPane();
        jt_pokedex = new javax.swing.JTree();
        jLabel19 = new javax.swing.JLabel();
        cb_velocidad = new javax.swing.JComboBox();
        jLabel17 = new javax.swing.JLabel();
        cb_tipo = new javax.swing.JComboBox<>();
        js_vida = new javax.swing.JSpinner();
        js_danop = new javax.swing.JSpinner();
        jPanel1 = new javax.swing.JPanel();
        jButton5 = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        cb_pokegrupos = new javax.swing.JComboBox<>();
        jButton6 = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        tf_nombrePokeG = new javax.swing.JTextField();
        jButton7 = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tabla1 = new javax.swing.JTable();
        jd_registrarse = new javax.swing.JDialog();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        tf_nombre = new javax.swing.JTextField();
        tf_usuarioC = new javax.swing.JTextField();
        tf_apellido = new javax.swing.JTextField();
        pf_contrasena = new javax.swing.JPasswordField();
        dc_fecha = new com.toedter.calendar.JDateChooser();
        jButton3 = new javax.swing.JButton();
        jb_colorFav = new javax.swing.JButton();
        bg_velocidad = new javax.swing.ButtonGroup();
        bg_tipoPok = new javax.swing.ButtonGroup();
        popup_modificar = new javax.swing.JPopupMenu();
        menu_popup = new javax.swing.JPopupMenu();
        opcion_eliminar = new javax.swing.JMenuItem();
        opcion_modifcar = new javax.swing.JMenuItem();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        tf_usuario = new javax.swing.JTextField();
        tf_contrasena = new javax.swing.JPasswordField();
        jButton1 = new javax.swing.JButton();
        jb_registrarse = new javax.swing.JButton();

        jLabel14.setText("Nombre");

        jLabel15.setText("Dano");

        jLabel16.setText("Pts. Vida");

        jButton4.setText(">");
        jButton4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton4MouseClicked(evt);
            }
        });

        jButton2.setText("Agregar a lista");
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton2MouseClicked(evt);
            }
        });

        jButton9.setText("Agregar a Arbol");
        jButton9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton9MouseClicked(evt);
            }
        });

        jl_pokemones.setModel(new DefaultListModel());
        jl_pokemones.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jl_pokemonesMouseClicked(evt);
            }
        });
        jl_pokemones.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jl_pokemonesKeyPressed(evt);
            }
        });
        jScrollPane1.setViewportView(jl_pokemones);

        javax.swing.tree.DefaultMutableTreeNode treeNode1 = new javax.swing.tree.DefaultMutableTreeNode("root");
        javax.swing.tree.DefaultMutableTreeNode treeNode2 = new javax.swing.tree.DefaultMutableTreeNode("Pokedex1");
        treeNode1.add(treeNode2);
        treeNode2 = new javax.swing.tree.DefaultMutableTreeNode("Pokedex2");
        treeNode1.add(treeNode2);
        treeNode2 = new javax.swing.tree.DefaultMutableTreeNode("Pokedex3");
        treeNode1.add(treeNode2);
        jt_pokedex.setModel(new javax.swing.tree.DefaultTreeModel(treeNode1));
        jt_pokedex.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jt_pokedexMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jt_pokedex);

        jLabel19.setText("Velocidad");

        cb_velocidad.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Baja", "Media", "Alta" }));

        jLabel17.setText("Tipo");

        cb_tipo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Electricidad", "Venenoso", "Psiquico", "Fantasma" }));
        cb_tipo.setSelectedIndex(-1);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(tf_nombrep, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(js_danop, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(js_vida, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel14)
                                .addGap(71, 71, 71)
                                .addComponent(jLabel15))
                            .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 234, Short.MAX_VALUE)
                                    .addComponent(jButton9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(49, 49, 49)
                                .addComponent(jLabel16))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cb_velocidad, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26)
                        .addComponent(jLabel17)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cb_tipo, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(52, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(jLabel15)
                    .addComponent(jLabel16))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tf_nombrep, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(js_vida, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(js_danop, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cb_velocidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel17)
                    .addComponent(cb_tipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(84, 84, 84)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton9, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
                    .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(11, 11, 11)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(98, 98, 98)
                        .addComponent(jButton4))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(62, Short.MAX_VALUE))
        );

        jTabbedPane4.addTab("Pokemones", jPanel2);

        jButton5.setText("Salir de PokeGrupo");

        jLabel11.setText("Unirse a PokeGrupo");

        cb_pokegrupos.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cb_pokegruposItemStateChanged(evt);
            }
        });

        jButton6.setText("Unirme");
        jButton6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton6MouseClicked(evt);
            }
        });

        jLabel12.setText("Crear PokeGrupo");

        jButton7.setText("Crear");
        jButton7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton7MouseClicked(evt);
            }
        });

        jLabel13.setText("Miembros");

        tabla1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nombre"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane3.setViewportView(tabla1);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel11)
                    .addComponent(cb_pokegrupos, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel12)
                    .addComponent(tf_nombrePokeG)
                    .addComponent(jButton7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(39, 39, 39)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel13)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 268, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(45, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton5)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(jLabel13))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(cb_pokegrupos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton6)
                        .addGap(32, 32, 32)
                        .addComponent(jLabel12)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tf_nombrePokeG, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton7))
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(298, Short.MAX_VALUE))
        );

        jTabbedPane4.addTab("PokeGrupo", jPanel1);

        javax.swing.GroupLayout jd_ingresarLayout = new javax.swing.GroupLayout(jd_ingresar.getContentPane());
        jd_ingresar.getContentPane().setLayout(jd_ingresarLayout);
        jd_ingresarLayout.setHorizontalGroup(
            jd_ingresarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_ingresarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane4))
        );
        jd_ingresarLayout.setVerticalGroup(
            jd_ingresarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_ingresarLayout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(jTabbedPane4)
                .addContainerGap())
        );

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel4.setText("Crear cuenta");

        jLabel5.setText("Nombre");

        jLabel6.setText("Usuario");

        jLabel7.setText("Apellido");

        jLabel8.setText("Contrasena");

        jLabel9.setText("Fecha (dd/mm/yyyy)");

        jLabel10.setText("Color Favorito");

        jButton3.setText("Registrarme");
        jButton3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton3MouseClicked(evt);
            }
        });

        jb_colorFav.setText("Color Favorito");
        jb_colorFav.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jb_colorFavMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jd_registrarseLayout = new javax.swing.GroupLayout(jd_registrarse.getContentPane());
        jd_registrarse.getContentPane().setLayout(jd_registrarseLayout);
        jd_registrarseLayout.setHorizontalGroup(
            jd_registrarseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_registrarseLayout.createSequentialGroup()
                .addGroup(jd_registrarseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jd_registrarseLayout.createSequentialGroup()
                        .addGap(148, 148, 148)
                        .addComponent(jLabel4))
                    .addGroup(jd_registrarseLayout.createSequentialGroup()
                        .addGap(66, 66, 66)
                        .addGroup(jd_registrarseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jd_registrarseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel9)
                                .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.LEADING))
                            .addComponent(tf_apellido)
                            .addComponent(tf_nombre)
                            .addComponent(dc_fecha, javax.swing.GroupLayout.DEFAULT_SIZE, 123, Short.MAX_VALUE))
                        .addGap(68, 68, 68)
                        .addGroup(jd_registrarseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel8)
                            .addComponent(jLabel6)
                            .addComponent(jLabel10)
                            .addComponent(tf_usuarioC)
                            .addComponent(pf_contrasena)
                            .addComponent(jb_colorFav, javax.swing.GroupLayout.DEFAULT_SIZE, 131, Short.MAX_VALUE))))
                .addContainerGap(61, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jd_registrarseLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jButton3)
                .addGap(52, 52, 52))
        );
        jd_registrarseLayout.setVerticalGroup(
            jd_registrarseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_registrarseLayout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(jLabel4)
                .addGap(31, 31, 31)
                .addGroup(jd_registrarseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6))
                .addGap(3, 3, 3)
                .addGroup(jd_registrarseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tf_nombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tf_usuarioC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jd_registrarseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jd_registrarseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tf_apellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pf_contrasena, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jd_registrarseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(jLabel10))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jd_registrarseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(dc_fecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jb_colorFav))
                .addGap(18, 18, 18)
                .addComponent(jButton3)
                .addContainerGap(26, Short.MAX_VALUE))
        );

        opcion_eliminar.setText("jMenuItem1");
        opcion_eliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opcion_eliminarActionPerformed(evt);
            }
        });

        opcion_modifcar.setText("jMenuItem2");
        opcion_modifcar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opcion_modifcarActionPerformed(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setText("LogIn");

        jLabel2.setText("Usuario");

        jLabel3.setText("Contrasena");

        jButton1.setText("Ingresar");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });

        jb_registrarse.setText("Registrarse");
        jb_registrarse.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jb_registrarseMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(116, 116, 116)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jb_registrarse)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(17, 17, 17))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel1)
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel3)
                                .addComponent(jLabel2))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(tf_usuario, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(tf_contrasena, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(143, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(jLabel1)
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(tf_usuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(tf_contrasena, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jb_registrarse)
                    .addComponent(jButton1))
                .addContainerGap(128, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        // TODO add your handling code here:
        
        if (tf_usuario.getText().equals(u)  &&  tf_contrasena.getText().equals(p) || 
                tf_usuario.getText().equals(l)  &&  tf_contrasena.getText().equals(u) ) {
            tf_usuario.setText("");
            tf_contrasena.setText("");
            openJDL();
        } else {
            JOptionPane.showMessageDialog(this, "El usuario no existe.");
        }
    }//GEN-LAST:event_jButton1MouseClicked

    private void jButton3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton3MouseClicked
        // TODO add your handling code here:
        String nombre, apellido, usuario, contrasena;
        Date fechaNacimiento;
        Color colorFav;
        ArrayList<Pokedex> pokedexes = new ArrayList(3); 
        try {     
            //codigo = Integer.parseInt(tf_codigo.getText());
            nombre = tf_nombre.getText();
            apellido = tf_apellido.getText();
            usuario = tf_usuario.getText();
            contrasena = tf_contrasena.getText();
            fechaNacimiento = dc_fecha.getDate();
            colorFav = jb_colorFav.getBackground(); 
            
            //if (pb_amigos.getValue() < 10) { 
                Usuario x = new Usuario(nombre, apellido, usuario, contrasena, fechaNacimiento, colorFav);
                lista.add(x);
                
                /*DefaultComboBoxModel dc=
                    (DefaultComboBoxModel) cb_amigos.getModel();
                dc.addElement(x);
                cb_amigos.setModel(dc);*/
                

                /*pb_amigos.setValue(lista.size());
                pb_amigos.setString(
                   Integer.toString(pb_amigos.getValue() * 100 / 10) + "%"
                );*/
                JOptionPane.showMessageDialog(this,
                        "Usuario registrado exitosamente.");
                } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this,
                 "Ocurrio un error y no se guardaron los datos");
        } 
    }//GEN-LAST:event_jButton3MouseClicked

    private void jb_registrarseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jb_registrarseMouseClicked
        // TODO add your handling code here:
        registrarseJDL();
    }//GEN-LAST:event_jb_registrarseMouseClicked

    private void jButton7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton7MouseClicked
        // TODO add your handling code here:
        //CREAR POKEGRUPOOOO 
        String nombre;
        ArrayList<Usuario> miembros = new ArrayList();
        Date fecha_creacion; 
        try {     
            //codigo = Integer.parseInt(tf_codigo.getText());
            nombre = tf_nombrePokeG.getText();
            fecha_creacion = dc_fecha.getDate(); 
            
            //if (pb_amigos.getValue() < 10) { 
                PokeGrupo x = new PokeGrupo(nombre, fecha_creacion);
                inventario.add(x);
                
                DefaultComboBoxModel dc=
                    (DefaultComboBoxModel) cb_pokegrupos.getModel();
                dc.addElement(x);
                cb_pokegrupos.setModel(dc);
                

                /*pb_amigos.setValue(lista.size());
                pb_amigos.setString(
                   Integer.toString(pb_amigos.getValue() * 100 / 10) + "%"
                );*/
                
                JOptionPane.showMessageDialog(this,
                        "Usuario registrado exitosamente.");
                } catch (Exception e) {
                    e.printStackTrace();
                    JOptionPane.showMessageDialog(this,
                        "Ocurrio un error y no se guardaron los datos");
        }
    }//GEN-LAST:event_jButton7MouseClicked

    private void cb_pokegruposItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cb_pokegruposItemStateChanged
        // TODO add your handling code here:
        if (evt.getStateChange() == 2) {
                PokeGrupo s = (PokeGrupo)
                        cb_pokegrupos.getSelectedItem();
                Object[] newrow = {
                    s.getNombre()
                };                
                DefaultTableModel modelo
                        = (DefaultTableModel) tabla1.getModel();
                modelo.addRow(newrow);
                tabla1.setModel(modelo);               
                //tf_edad_maxima.setText(maxima_edad());               
            }               
            
    }//GEN-LAST:event_cb_pokegruposItemStateChanged

    private void jButton6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton6MouseClicked
        // TODO add your handling code here:
        //UNIRME A POKE GRUPOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO
        
        
        /*
        String nombre, apellido, usuario, contrasena;
        Date fechaNacimiento;
        Color colorFav;
        ArrayList<Pokedex> pokedexes = new ArrayList(3);
        try {     
            nombre = tf_nombre.getText();
            apellido = tf_apellido.getText();
            usuario = tf_usuario.getText();
            contrasena = tf_contrasena.getText();
            fechaNacimiento = dc_fecha.getDate();
            colorFav = jb_colorFav.getBackground();
               
             
                Usuario x = new Usuario(nombre, apellido, usuario, contrasena, fechaNacimiento, colorFav);
                lista.add(x);
                
                JOptionPane.showMessageDialog(this,
                        "Usuario registrado exitosamente");
                
                tf_nombre.setText("");
                tf_apellido.setText("");
                tf_usuario.setText("");
                tf_contrasena.setText("");
                dc_fecha.setDate(new Date());
                jb_colorFav.setBackground(Color.red);
            
            
            
        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this,
                 "Ocurrio un error y no se guardaron los datos");
        }*/
        
    }//GEN-LAST:event_jButton6MouseClicked

    private void jButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseClicked
        // TODO add your handling code here:
        DefaultListModel modelo
                = (DefaultListModel) jl_pokemones.getModel();

        modelo.addElement (new Pokemon(tf_nombrep.getText(),
                             (String) cb_velocidad.getSelectedItem(),
                             (String) cb_tipo.getSelectedItem(),
                             (Integer)js_danop.getValue(),
                                (Integer) js_vida.getValue()
                        )
        );
        jl_pokemones.setModel(modelo);
        tf_nombre.setText("");
        cb_velocidad.setSelectedItem(o);
        cb_tipo.setSelectedItem(o);
        js_danop.setValue(o);
        js_vida.setValue(o);
        //sp_edad.setValue(20);
        //cb_nacionalidad.setSelectedIndex(0);
        
        /*
        DefaultListModel modelo
                = (DefaultListModel) jl_pokemones.getModel();

        modelo.addElement(new Pokemon(tf_nombrep.getText(),
                (String) cb_velocidad.getSelectedItem(),
                (String) js_danop.getValue(),
                (Integer) js_vida.getValue(),
                (Integer) cb_tipo.getSelectedItem()
                
        )
        );
        jl_pokemones.setModel(modelo);
        tf_nombrep.setText("");
        js_danop.setValue(50);
        js_danop.setValue(100);
        cb_tipo.setSelectedIndex(1);
        cb_velocidad.setSelectedIndex(1);*/
    }//GEN-LAST:event_jButton2MouseClicked

    private void jl_pokemonesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jl_pokemonesMouseClicked
        // TODO add your handling code here:
        if (jl_pokemones.getSelectedIndex() >= 0) {
            if (evt.isMetaDown()) {
                popup_modificar.show(evt.getComponent(),
                    evt.getX(), evt.getY()); 

            }
        }
    }//GEN-LAST:event_jl_pokemonesMouseClicked

    private void jl_pokemonesKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jl_pokemonesKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == evt.VK_DELETE) {
           if (jl_pokemones.getSelectedIndex() >= 0) {
                DefaultListModel modelo
                        = (DefaultListModel) jl_pokemones.getModel();
                modelo.remove(jl_pokemones.getSelectedIndex());
                jl_pokemones.setModel(modelo);
                JOptionPane.showMessageDialog(this,
                        "Eliminado exitosamente");
                
            } 
        }
    }//GEN-LAST:event_jl_pokemonesKeyPressed

    private void jt_pokedexMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jt_pokedexMouseClicked
        // TODO add your handling code here:
        
        if (evt.isMetaDown()) {
            //seleccionar un nodo con click derecho
            int row = jt_pokedex.getClosestRowForLocation(
                    evt.getX(), evt.getY());
            jt_pokedex.setSelectionRow(row);
            Object v1
                    = jt_pokedex.getSelectionPath().
                    getLastPathComponent();
            nodo_seleccionado = (DefaultMutableTreeNode) v1;
            if (nodo_seleccionado.getUserObject() instanceof Pokemon) {
                pokemon_seleccionado
                        = (Pokemon) nodo_seleccionado.
                        getUserObject();
                menu_popup.show(evt.getComponent(),
                        evt.getX(), evt.getY());
            }

        }
    }//GEN-LAST:event_jt_pokedexMouseClicked

    private void jb_colorFavMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jb_colorFavMouseClicked
        // TODO add your handling code here:
        jb_colorFav.setBackground(
                JColorChooser.showDialog(
                        this, "Seleccione un color", Color.yellow)
        );
    }//GEN-LAST:event_jb_colorFavMouseClicked

    private void jButton9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton9MouseClicked
        // TODO add your handling code here:
        DefaultTreeModel m = (DefaultTreeModel) jt_pokedex.getModel();
        DefaultMutableTreeNode raiz
                = (DefaultMutableTreeNode) m.getRoot();
        DefaultMutableTreeNode nodo_persona;
        nodo_persona
                = new DefaultMutableTreeNode(
                        new Pokemon(tf_nombrep.getText(),
                             (String) cb_velocidad.getSelectedItem(),
                             (String) cb_tipo.getSelectedItem(),
                             (Integer)js_danop.getValue(),
                                (Integer) js_vida.getValue()
                        )
                );
        
        DefaultMutableTreeNode tipo;
        tipo = new DefaultMutableTreeNode(
                new DefaultMutableTreeNode(
                      (String)  cb_tipo.getSelectedItem()
                )
        );        
        DefaultMutableTreeNode nombre;
        nombre = new DefaultMutableTreeNode(
               (String) tf_nombrep.getText()
        );
        tipo.add(nombre);
        nodo_persona.add(tipo);
        raiz.add(nodo_persona);
        m.reload();
        tf_nombrep.setText("");
    }//GEN-LAST:event_jButton9MouseClicked

    private void jButton4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton4MouseClicked
        // TODO add your handling code here:
        
        if (jl_pokemones.getSelectedIndex() >= 0) {
            DefaultTreeModel modeloARBOL
                    = (DefaultTreeModel) jt_pokedex.getModel();
            DefaultMutableTreeNode raiz
                    = (DefaultMutableTreeNode) modeloARBOL.getRoot();
            //obtener la persona a guardar
            DefaultListModel modeloLISTA
                    = (DefaultListModel) jl_pokemones.getModel();
            
            String nombre, velocidad, tipo;
            int dano,vida;
            nombre 
                    = ((Pokemon) modeloLISTA.get(
                    jl_pokemones.getSelectedIndex())).
                    getNombre();
            velocidad = ((Pokemon) modeloLISTA.get(
                    jl_pokemones.getSelectedIndex())).
                    getVelocidad();
            tipo = ((Pokemon) modeloLISTA.get(
                    jl_pokemones.getSelectedIndex())).
                    getTipo();
            dano = ((Pokemon) modeloLISTA.get(
                    jl_pokemones.getSelectedIndex())).
                    getDano();
            vida = ((Pokemon) modeloLISTA.get(
                    jl_pokemones.getSelectedIndex())).
                    getVida();
            
            int centinela = -1;           
            for (int i = 0; i < raiz.getChildCount(); i++) {
                if (raiz.getChildAt(i).toString().
                        equals(velocidad)) {
                    DefaultMutableTreeNode p
                            = new DefaultMutableTreeNode(
                                    new Pokemon(nombre, velocidad, tipo, dano, vida)
                            );
                    ((DefaultMutableTreeNode) raiz.getChildAt(i)).add(p);
                    centinela = 1;
                } //fin if
            } //fin for  
            
            if (centinela == -1) {
                DefaultMutableTreeNode n
                        = new DefaultMutableTreeNode(velocidad);
                DefaultMutableTreeNode p
                        = new DefaultMutableTreeNode(
                                new Pokemon(nombre, velocidad, tipo, dano, vida)
                        );
                n.add(p);
                raiz.add(n);
            }  // fin if          
            modeloARBOL.reload();
            
                        
        } else {
            JOptionPane.showMessageDialog(this,
                    "No hay pokemon seleccionado");
        }
    }//GEN-LAST:event_jButton4MouseClicked

    private void opcion_eliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opcion_eliminarActionPerformed
        // TODO add your handling code here:
        int response = JOptionPane.showConfirmDialog(
                this,
                "Seguro de Eliminar?",
                "Confirm",
                JOptionPane.YES_NO_OPTION,
                JOptionPane.QUESTION_MESSAGE);

        if (response == JOptionPane.OK_OPTION) {
            DefaultTreeModel m
                    = (DefaultTreeModel) jt_pokedex.getModel();
            m.removeNodeFromParent(
                    nodo_seleccionado);
            m.reload();
        }
    }//GEN-LAST:event_opcion_eliminarActionPerformed

    private void opcion_modifcarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opcion_modifcarActionPerformed
        // TODO add your handling code here:
        DefaultTreeModel m
                = (DefaultTreeModel) jt_pokedex.getModel();
        pokemon_seleccionado.setNombre(
                JOptionPane.showInputDialog("Nuevo nombre"));
        m.reload();
    }//GEN-LAST:event_opcion_modifcarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Lab6P2_MarioCalix_22041098.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Lab6P2_MarioCalix_22041098.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Lab6P2_MarioCalix_22041098.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Lab6P2_MarioCalix_22041098.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Lab6P2_MarioCalix_22041098().setVisible(true);
            }
        });
    }
    
    private void openJDL(){
        jd_ingresar.pack(); //hacer grande
        jd_ingresar.setLocationRelativeTo(this); //centrar pagina con la otra
        jd_ingresar.setModal(true); //bloquear 
        jd_ingresar.setVisible(true); //mostrar la ventana
    }
    
    private void registrarseJDL(){
        jd_registrarse.pack(); //hacer grande
        jd_registrarse.setLocationRelativeTo(this); //centrar pagina con la otra
        jd_registrarse.setModal(true); //bloquear 
        jd_registrarse.setVisible(true); //mostrar la ventana
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup bg_tipoPok;
    private javax.swing.ButtonGroup bg_velocidad;
    private javax.swing.JComboBox<String> cb_pokegrupos;
    private javax.swing.JComboBox<String> cb_tipo;
    private javax.swing.JComboBox cb_velocidad;
    private com.toedter.calendar.JDateChooser dc_fecha;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTabbedPane jTabbedPane4;
    private javax.swing.JButton jb_colorFav;
    private javax.swing.JButton jb_registrarse;
    private javax.swing.JDialog jd_ingresar;
    private javax.swing.JDialog jd_registrarse;
    private javax.swing.JList jl_pokemones;
    private javax.swing.JSpinner js_danop;
    private javax.swing.JSpinner js_vida;
    private javax.swing.JTree jt_pokedex;
    private javax.swing.JPopupMenu menu_popup;
    private javax.swing.JMenuItem opcion_eliminar;
    private javax.swing.JMenuItem opcion_modifcar;
    private javax.swing.JPasswordField pf_contrasena;
    private javax.swing.JPopupMenu popup_modificar;
    private javax.swing.JTable tabla1;
    private javax.swing.JTextField tf_apellido;
    private javax.swing.JPasswordField tf_contrasena;
    private javax.swing.JTextField tf_nombre;
    private javax.swing.JTextField tf_nombrePokeG;
    private javax.swing.JTextField tf_nombrep;
    private javax.swing.JTextField tf_usuario;
    private javax.swing.JTextField tf_usuarioC;
    // End of variables declaration//GEN-END:variables

    String u="mario", p="123",l="james",o="321";
    ArrayList<Usuario> lista = new ArrayList();
    ArrayList<PokeGrupo> inventario = new ArrayList();
    DefaultMutableTreeNode nodo_seleccionado;
    Pokemon pokemon_seleccionado;

}
